# Generated by Django 4.0.6 on 2022-07-22 07:45

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('UI/UX', 'UI/UX'), ('HTML/CSS', 'HTML/CSS'), ('Postgres', 'Postgres')], max_length=30)),
                ('what_i_do', ckeditor.fields.RichTextField()),
                ('about', ckeditor.fields.RichTextField()),
                ('facebook_link', models.URLField(max_length=100)),
                ('github_link', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PastProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_link', models.URLField(max_length=100)),
            ],
        ),
    ]
