# Generated by Django 4.0.6 on 2022-07-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastProject',
            new_name='Project',
        ),
    ]
