# Generated by Django 4.0.6 on 2022-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_pastproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
