# Generated by Django 4.0.6 on 2022-07-23 05:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_detail_photo_project_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
