# Generated by Django 4.0.6 on 2022-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='descripttion',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
