# Generated by Django 4.0.6 on 2022-07-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_project_description_project_descripttion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='descripttion',
        ),
    ]
